/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20 } from "./IERC20";
export type { ISatsumaLPVault } from "./ISatsumaLPVault";
export type { SatsumaAdapter } from "./SatsumaAdapter";
