/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lavaCrossChainVaultSol from "./LavaCrossChainVault.sol";
export type { lavaCrossChainVaultSol };
import type * as lavaPortfolioVaultSol from "./LavaPortfolioVault.sol";
export type { lavaPortfolioVaultSol };
import type * as magmaVaultSol from "./MagmaVault.sol";
export type { magmaVaultSol };
import type * as mockBridgeSol from "./MockBridge.sol";
export type { mockBridgeSol };
import type * as mockInstitutionalYieldSourceSol from "./MockInstitutionalYieldSource.sol";
export type { mockInstitutionalYieldSourceSol };
import type * as mockSatsumaRouterSol from "./MockSatsumaRouter.sol";
export type { mockSatsumaRouterSol };
import type * as mockZentraPoolV2Sol from "./MockZentraPoolV2.sol";
export type { mockZentraPoolV2Sol };
import type * as obsidianVaultSol from "./ObsidianVault.sol";
export type { obsidianVaultSol };
import type * as adapters from "./adapters";
export type { adapters };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as mockSatsumaLpVaultSol from "./mockSatsumaLPVault.sol";
export type { mockSatsumaLpVaultSol };
import type * as mockZentraPoolSol from "./mockZentraPool.sol";
export type { mockZentraPoolSol };
import type * as zcBtcSol from "./zcBTC.sol";
export type { zcBtcSol };
export type { MockUSDC } from "./MockUSDC";
export type { MockWcBTC } from "./MockWcBTC";
