/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IYieldSourceView,
  IYieldSourceViewInterface,
} from "../../../../contracts/adapters/CrossChainAdapter.sol/IYieldSourceView";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "totalAssets",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IYieldSourceView__factory {
  static readonly abi = _abi;
  static createInterface(): IYieldSourceViewInterface {
    return new Interface(_abi) as IYieldSourceViewInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IYieldSourceView {
    return new Contract(address, _abi, runner) as unknown as IYieldSourceView;
  }
}
