/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as crossChainAdapterSol from "./CrossChainAdapter.sol";
export type { crossChainAdapterSol };
import type * as satsumaAdapterSol from "./SatsumaAdapter.sol";
export type { satsumaAdapterSol };
import type * as zentraAdapterSol from "./ZentraAdapter.sol";
export type { zentraAdapterSol };
