/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISatsumaLPVault,
  ISatsumaLPVaultInterface,
} from "../../../../contracts/adapters/SatsumaAdapter.sol/ISatsumaLPVault";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
    ],
    name: "deposit",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "totalAssets",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "withdraw",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISatsumaLPVault__factory {
  static readonly abi = _abi;
  static createInterface(): ISatsumaLPVaultInterface {
    return new Interface(_abi) as ISatsumaLPVaultInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISatsumaLPVault {
    return new Contract(address, _abi, runner) as unknown as ISatsumaLPVault;
  }
}
