/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISatsumaRouter,
  ISatsumaRouterInterface,
} from "../../../contracts/MagmaVault.sol/ISatsumaRouter";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "tokenIn",
            type: "address",
          },
          {
            internalType: "address",
            name: "tokenOut",
            type: "address",
          },
          {
            internalType: "uint24",
            name: "fee",
            type: "uint24",
          },
          {
            internalType: "address",
            name: "recipient",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "deadline",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "amountIn",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "amountOutMinimum",
            type: "uint256",
          },
          {
            internalType: "uint160",
            name: "sqrtPriceLimitX96",
            type: "uint160",
          },
        ],
        internalType: "struct ISatsumaRouter.ExactInputSingleParams",
        name: "",
        type: "tuple",
      },
    ],
    name: "exactInputSingle",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class ISatsumaRouter__factory {
  static readonly abi = _abi;
  static createInterface(): ISatsumaRouterInterface {
    return new Interface(_abi) as ISatsumaRouterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISatsumaRouter {
    return new Contract(address, _abi, runner) as unknown as ISatsumaRouter;
  }
}
