/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20 } from "./IERC20";
export type { IPriceOracle } from "./IPriceOracle";
export type { ISatsumaRouter } from "./ISatsumaRouter";
export type { IUSDC } from "./IUSDC";
export type { IWcBTC } from "./IWcBTC";
export type { IZentraPool } from "./IZentraPool";
export type { LavaMaximizedVault } from "./LavaMaximizedVault";
