/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IZentraPoolV2,
  IZentraPoolV2Interface,
} from "../../../../contracts/adapters/ZentraAdapter.sol/IZentraPoolV2";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "onBehalf",
        type: "address",
      },
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    name: "supply",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "withdraw",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IZentraPoolV2__factory {
  static readonly abi = _abi;
  static createInterface(): IZentraPoolV2Interface {
    return new Interface(_abi) as IZentraPoolV2Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IZentraPoolV2 {
    return new Contract(address, _abi, runner) as unknown as IZentraPoolV2;
  }
}
